### ISSUE TITLE
New naming convention

### ISSUE THREAD

**Issue by roofburner** [michaelarnauts/home-assistant-comfoconnect#16]
Hi,

I installed the custom Home Assistant Zehnder ComfoAirQ integration (https://github.com/michaelarnauts/home-assistant-comfoconnect). I experienced the change in naming.

e.g. sensor.comfoairq_supply_humidity becomes sensor.supply_humidity

Is this a strategic decision? Why is the "comfoairq_" dropped?

I would like to keep the reference to the device providing the sensors.

e.g. sensor.openweathermap_humidity => sensor proviced by the OpenWeatherMap device.

In the new naming convention, the device reference gets lost.

Kind regards,

Stijn

**Comment by roofburner** [comment]
OK, Michael. Is it OK to keep this ticket open until fixed? Maybe mark it as bug?

**Comment by michaelarnauts** [comment]
This has been fixed in https://github.com/michaelarnauts/home-assistant-comfoconnect/commit/bbeb267656dd78ea591d1c870128825517020f32

It's now using the `_attr_has_entity_name = True` property, so Home Assistant creates the correct entity_id.

**Comment by roofburner** [comment]
Dear Michael,

I have upgraded the Zehnder ComfoAirQ integration to a308546, but I still see sensors like sensor.outside_temperature. No reference in the name to ComfoAirQ. Do I miss something?

Kind regards,

Stijn

**Comment by roofburner** [comment]
Real question: when will I be able to install bbeb267?

**Comment by michaelarnauts** [comment]
a308546 is the latest, and contains all the other fixes.

You probably don't see the new names since Home Assistant kept the existing IDs. I guess if you remove the integration and add it again, you'll get the new IDs.

**Comment by roofburner** [comment]
OK, Michael, I was confused about the numbering.
I removed/added the integration. Now all sensors seem to have their correct name.

Thx!

**Comment by michaelarnauts** [comment]
> OK, Michael, I was confused about the numbering. I removed/added the integration. Now all sensors seem to have their correct name.
> 
> Thx!

Yeah, I better had used real releases with a changelog, but then again, I actually want to merge all my changes back to Home Assistant. It's just that this also takes a lot of time and effort :(
